# 서버 포트 설정
server:
  port: 8080
---
# database 연동 설정
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/practice?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dhgusdl1**
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect # 해당 SQL로 코드를 해준다.
    open-in-view: false
    hibernate:
      ddl-auto: none # 스프링이 시작할 때 DB에 있는 테이블을 어떻게 처리할지 create:삭제후 다시 생성, create-drop: 스프링이 종료될때 제거
                    # update: 객체와 테이블이 다른 부분만 변경, validate:객체와 테이블이 동일한지 확인, none:조치 x
      show-sql: true
      format_sql: true